#!/usr/bin/env node

var program = require('commander')
	.arguments('<file>')
	.option('-o, --out [file]', 'optional output file path')
	.option('-n, --namespace [string]', 'optional C++ namespace.')
	.option('--no-coffee', 'disable CoffeeScript support')
	.parse(process.argv)

if(!program.args.length) return program.help()
if(program.coffee) require('coffeescript/register')
require('./cpp').run(program.args[0], program.out, program.namespace)
